__init__.py
from flask import Flask
from routes.render import render_blueprint
from routes.api.setup import api_blueprint
import contextProcessor


app = Flask(__name__)

app.register_blueprint(render_blueprint)
app.register_blueprint(api_blueprint)

app.context_processor(contextProcessor.is_auth)

app.run(host="0.0.0.0",
        port=8000,
        debug=True)

routes/render.py
from flask import Flask, Blueprint, render_template, request, redirect, url_for, make_response
from extensions import connect
from database.user import User
from database.baseTable import BaseTable, NoResultsFoundException
from decorators import only_auth

render_blueprint = Blueprint(
    "render",
    __name__,
    url_prefix="/"
)

def get_login():
    """
    Tato trasa je propojena s funkcí get_login, která renderuje šablonu ‘login.html’. Také předává chybovou zprávu, pokud je nějaká v argumentech požadavku.
    """
    return render_template('login.html',**{
        "error_message": request.args.get("error_message", None)
    })
render_blueprint.add_url_rule("login/","get_login",get_login,methods=["GET"])

def post_login():
    """
    Tato trasa je propojena s funkcí post_login, která zpracovává přihlašovací údaje uživatele. 
    Pokud jsou údaje správné, uživatel je přesměrován na požadovanou stránku nebo na úvodní stránku. Pokud jsou údaje nesprávné, uživatel je přesměrován zpět na přihlašovací stránku s chybovou zprávou.
    """
    redirect_page:str = request.args.get("redirect_page", None)
    form_username: str = request.form["username"]
    form_password: str = request.form["password"]
    try:
        user = User.read_one_username(connect(), form_username)
    except NoResultsFoundException as e:
        return redirect(url_for('render.get_login', redirect_page=redirect_page, error_message="Špatné uživatelské jméno"))
    print(str(user))
    if user.password == form_password:
        if not redirect_page is None:
            response = make_response(redirect(redirect_page))
        else:
            print("redirect index")
            response = make_response(redirect(url_for("render.index")))
            print(url_for("render.index"))
        response.set_cookie("user_id",str(user.id))
        return response
    return redirect(url_for('render.get_login', redirect_page=redirect_page, error_message="Špatné heslo"))
render_blueprint.add_url_rule("login/","post_login",post_login,methods=["POST"])

@only_auth()
def get_logout():
    """
    Tato trasa je propojena s funkcí get_logout, která odstraní cookie user_id a přesměruje uživatele na přihlašovací stránku
    """
    response = make_response(redirect(url_for("render.get_login")))
    response.delete_cookie("user_id")
    return response
render_blueprint.add_url_rule("logout/","get_logout",get_logout,methods=["GET"])

@only_auth()
def index():
    """
    Tato trasa je propojena s funkcí register, která renderuje šablonu ‘register.html’. Tato trasa je také chráněna dekorátorem only_auth.
    """
    return render_template("prvni_stranka.html")
render_blueprint.add_url_rule("","index",index,methods=["GET"])

@only_auth()
def register():
    """
    Tato trasa je propojena s funkcí register, která renderuje šablonu ‘register.html’. Tato trasa je také chráněna dekorátorem only_auth.
    """
    return render_template("register.html")
render_blueprint.add_url_rule("registrace/","register", register, methods=["GET"])

def show():
    """
    Tato trasa je propojena s funkcí show, která renderuje šablonu ‘show.html’.
    """
    return render_template('show.html')
render_blueprint.add_url_rule("show/","show", show, methods=["GET"])

templates/druha_stranka.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <link rel="stylesheet" href="/static/mujstyl.css" />
    <title>Druhá stránka</title>
    <style>
        body, html{
            margin: 0;
        }
    </style>
</head>
<body>

<h1>Druhá stránka se zprávou</h1>

<p>{{ zprava }}</p>

<p><a href="/">Jdi zpět</a>.</p>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='body.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='login/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='login/switch.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='navbar.css') }}">
    <style>
        html,body{
            margin: 0;
        }
    </style>
</head>
<body>
  {% include 'navbar.html' %}
  <script src="{{ url_for('static', filename='login/script.js') }}"></script>
  <div id="page_content">
    {% if error_message is defined and not error_message == None %}
    <div class="error" id="error_div">
      <p>{{error_message}}</p>
      <button class="close-btn" onclick="close_button()">Zavřít</button>
    </div>
    {% endif %}
    <form method="POST" autocomplete="off" class="form">
      <h2>Přihlásit se</h2>
      <div class="input element">
        <input name="username" placeholder="Uživatelské jméno" type="text"
        {% if username is defined %}value={{username}}{% endif %}
        >
      </div>
      <div class="input element">
        <input name="password" id="password_input" placeholder="Heslo" type="password">
      </div>
      <div class="container_switch">
        <label class="switch">
          <input type="checkbox" onclick="switch_function()">
          <span class="slider"></span>
        </label>
        <p id="switch_paragraph">zobrazit heslo</p>
      </div>
      <div class="element">
        <input type="submit" value="přihlásit se"></input>
      </div>
    </form>
  </div>
</body>
</html>

templates/navbar.html
<nav>
    <ul>
        <li id="account">
            {% if is_auth() == true %}
            <a href= "{{url_for('render.get_logout')}}">odhlásit se</a>
            {% else %}
                <a href= "{{url_for('render.get_login')}}">přihlásit se</a>
            {% endif %}
        </li>
        <li id="menu">
            <a href= "{{url_for('render.index')}}">menu</a>
        </li>
        <li id="show">
            <a href= "{{url_for('render.show')}}">zobrazit</a>
        </li>
    </ul>
</nav>

templates/prvni_stranka.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <link rel="stylesheet" href="/static/mujstyl.css" />
    <link rel="stylesheet" href="{{ url_for('static', filename='navbar.css') }}">
    <script src="{{ url_for('static', filename='render/script.js') }}"></script>
    <title>Úvodní stránka</title>
    <style>
        body, html{
            margin: 0;
        }
    </style>
</head>
<body>
    {% include 'navbar.html' %}

    <h1>Rozsazení v lodích na vodáckém kurzu 2023 SPŠE Ječná</h1>

    <p>Ahoj světe!</p>
    <div id="canSwim">
        <span>Umím plavat</span>
    </div>
    <p><a href="{{ url_for('render.register') }}">Registrace</a>.</p>
    <div id="confirm">

    </div>
    <script>


        const user_id = getCookie('user_id');

        const cs = document.getElementById('canSwim')
        let tmp = document.createElement('input');
        tmp.type='checkbox'
        tmp.id='canSwim_input'
        cs.append(tmp)

        tmp.addEventListener('click', function () {
            fetch(
                '/api/user/canSwim/',
                {
                    method: 'POST',
                    headers: {
                        "Content-Type": "application/json",
                        "user-id": user_id
                    },
                    body:JSON.stringify({
                        'canSwim':tmp.checked,
                        'user': user_id
                    })
                }
            ).then(response => {
                if (response.status===200){
                    return response.json()
                }
                return {}
            }).then(data => {
                console.log('canSwim zapsáno')
                if (tmp.checked){
                    alert('Už umíš plavat')
                }else{
                    alert('Už neumíš plavat, tak se sem nehlas')
                }
            })
        })

        function postConfirm(sender, reciever){
            if(!document.getElementById('canSwim_input').checked){
                alert('Nehlas se když neumíš plavat!!!')
                throw new Error('Chyba')
            }
            console.log("post comfirm "+sender+" ==> "+reciever)
            return fetch(
                '/api/user/result/',
                {
                    method: 'POST',
                    headers: {
                        "Content-Type": "application/json",
                        "user-id": sender
                    },
                    body:JSON.stringify({
                        'sender':sender,
                        'reciever': reciever
                    })
                }

            ).then(response => {
                if (response.status===200){
                    return response.json()
                }
                return {}
            })
        }

        function getUsername(user_id){
            return fetch(
                '/api/user/'+user_id+'/',
                {
                    method: 'GET',
                    headers: {
                        "Content-Type": "application/json",
                        "user-id": user_id
                    },
                }

            )
            .then(response => {
                if (response.status === 200) { // Kontrola, zda je status 201 Created
                    return response.json();
                }
                throw new Error('Network response was not ok');
            })
            .then(data => {
                return data
            })
        }

        function getConfirms(){
            return fetch(
                '/api/user/my_requests/',
                {
                    method: 'GET',
                    headers: {
                        "Content-Type": "application/json",
                        "user-id": user_id
                    },
                }
            )
            .then(response => {
                if (response.status === 200) { // Kontrola, zda je status 201 Created
                    return response.json();
                }
                throw new Error('Network response was not ok');
            })
            .then(data => {
                return data['requests']
            })
            .catch(error => {
                console.error('Chyba: ' + error);
            });
        }


        const confirmDiv = document.getElementById("confirm");
        getUsername(user_id).then(data => {
            console.log(data)
            let tmp = document.getElementById('canSwim_input')
            tmp.checked=data['canSwim']
            if (data["finish"]===false){
                const confirms = getConfirms().then(data =>{
                    console.log(data)
                    for(let i=0; i<data.length; i++){
                        const button = document.createElement('button');
                        confirmDiv.append(button)
                        button.id='user_'+data[i]['user_id'];
                        getUsername(data[i]['user_id']).then(data => {
                            button.textContent=data['username'];
                        });
                        button.addEventListener(
                            'click',
                            function (){
                                try{
                                    postConfirm(user_id, data[i]['user_id']).then(data => {
                                        confirmDiv.innerHTML='';
                                        infoParagraph = document.createElement('p');
                                        infoParagraph.textContent = 'Byl jste už zapsán do systému'
                                        confirmDiv.append(infoParagraph)
                                        infoParagraph.style.color='green';
                                    });
                                }catch(e){
                                    console.log('nenastalo, protože jsi neplavec!!!')
                                }
                            }
                        )
                    }
                })
            }else{ //ukončeno
                infoParagraph = document.createElement('p');
                infoParagraph.textContent = 'Byl jste už zapsán do systému'
                confirmDiv.append(infoParagraph)
                infoParagraph.style.color='green';
            }
        })
        
    </script>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='navbar.css') }}">

    <script src="{{ url_for('static', filename='render/script.js') }}"></script>
    <title>Document</title>

    <style>
        html, body{
            margin: 0;
        }
    </style>
</head>
<body>
    {% include 'navbar.html' %}
    <h1>Registrace</h1>
    <div id="div_form" >
        <form action="">
            <div id="div_nickname">
                <input id="input_nickname" type="text" placeholder="Nickname" name="nick">
            </div>
            <div id="div_swimming">
                <label>Plavec</label><input  id="input_swimming" type="checkbox" name="je_plavec">
            </div>
            <div id="div_friend">
                <textarea id="input_friend" cols="30" rows="10" placeholder="Kamarád" name="kenoe_kamarad"></textarea>
            </div>
            <div id="div_buttons">
                <button type="button" id="btn_storno">Storno</button>
                <button type="button" id="btn_submit">Odelat</button>
            </div>
        </form>
    </div>
    <script>
        document.getElementById("btn_storno").addEventListener("click", function() {
            window.location = "/";
        });
        fetchUser(getCookie("user_id")).then(data => {
            console.log(data)
            console.log(data["finish"])
            if (!data["finish"]){
                document.getElementById("btn_submit").addEventListener("click", function() {
                    const data = {
                        "nick":document.getElementById("input_nickname").value,
                        "je_plavec":document.getElementById("input_swimming").checked,
                        "kanoe_kamarad":document.getElementById("input_friend").value
                    };
                    sendForm(data);
                });
                fetchUsername(getCookie("user_id"), document.getElementById("input_nickname"));
            }else{
                const tmp = document.getElementById('div_form');
                tmp.innerHTML='';
                tmp.innerHTML='<p style="color:green;">Byl jste už zapsán do systému</p>'
            }
        })
    </script>
</body>
</html>

templates/show.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="{{ url_for('static', filename='render/script.js') }}"></script>
    <link rel="stylesheet" href="{{ url_for('static', filename='navbar.css') }}">
    <title>Document</title>
    <style>
        html, body{
            margin: 0;
        }
        #content {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh; /* Výška viewportu */
          }
          
          table {
            border-collapse: collapse;
            width: 50%; /* Šířka tabulky */
          }
          
          table, th, td {
            border: 1px solid black;
            padding: 10px;
            text-align: center;
          }
    </style>
</head>
<body>
    {% include 'navbar.html' %}
    <div id="content">
        <table id="table">
            <tr>
                <th>1.žák</th>
                <th>2.žák</th>
            </tr>
        </table>
    </div>
    <script>
        const table = document.getElementById('table');
        fetchAllFinishedRegistrations().then(data => {
            for(let i=0; i<data.length; i++){
                const tr = document.createElement('tr');
                table.append(tr);
                const th1 = document.createElement('th');
                const th2 = document.createElement('th');
                tr.append(th1);
                tr.append(th2);
                th1.textContent=data[i]["u1"]
                th2.textContent=data[i]["u2"]

            }
        })
    </script>
</body>
</html>